name: Lint R Project
on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  lint:
    name: Lint R Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: Rscript -e 'install.packages("lintr")'

    - name: Lint R code
      run: Rscript -e 'lintr::lint_dir()'
